# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from logic import action

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\Documents\hieunt8\DataMapping\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def main():
    window = Tk()

    window.geometry("860x545")
    window.configure(bg="#85EAD8")

    canvas = Canvas(
        window,
        bg="#85EAD8",
        height=545,
        width=860,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )

    canvas.place(x=0, y=0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        430.0,
        272.0,
        image=image_image_1
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        205.5,
        233.0,
        image=entry_image_1
    )
    entry_1 = Text(
        bd=0,
        bg="#F1F5FF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=47.0,
        y=59.0,
        width=317.0,
        height=346.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        628.0,
        292.5,
        image=entry_image_2
    )
    entry_2 = Text(
        bd=0,
        bg="#EBF3FD",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=435.0,
        y=59.0,
        width=386.0,
        height=465.0
    )

    canvas.create_text(
        299.0,
        12.0,
        anchor="nw",
        text="Data Mapping",
        fill="#FFFFFF",
        font=("Inter", 32 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: action(entry_1, entry_2),
        relief="flat"
    )
    button_1.place(
        x=77.0,
        y=428.0,
        width=257.0,
        height=62.0
    )
    window.resizable(False, False)
    window.mainloop()


if __name__ == "__main__":
    main()
